name: Java Battleship Push Workflow

# Triggers only on Push to any branch
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the code from the branch
      - name: Checkout code
        uses: actions/checkout@v6

      # Set up Java 21 with Maven dependency caching
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"

      - name: Build and Test with Maven
        run: mvn -B clean verify checkstyle:checkstyle spotbugs:spotbugs pmd:pmd

      - name: Publish Checkstyle
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: '**/checkstyle-result.xml'

      - name: Publish SpotBugs
        uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: '**/spotbugsXml.xml'
          
      - name: Publish PMD
        uses: jwgmeligmeyling/pmd-github-action@master
        with:
          path: '**/pmd.xml'
  
      # Upload the compiled JAR as a downloadable artifact
      - name: Upload JAR file
        uses: actions/upload-artifact@v6
        with:
          name: battleship-jar
          path: target/*.jar

      - name: Debug - List target directory
        if: always()
        run: find target -type f -name "*.html" -o -name "*.xml" | sort

      #UPLOAD ALL ANALYSIS ARTIFACT
      - name: Upload Analysis Report
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: Analysis report
          path: |
            target/reports/pmd.html
            target/reports/cpd.html
            target/reports/checkstyle.html
            target/site/spotbugs.html
            taget/spotbugsXml.html
            target/spotbugs.html